# Generated by Django 4.1.13 on 2024-09-08 04:27

import datetime
from django.db import migrations, models
import djongo.models.fields
import question_generator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedITQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('options', djongo.models.fields.JSONField()),
                ('correct_answer', models.CharField(max_length=100)),
                ('paperId', models.IntegerField()),
                ('generated_datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'generated_IT_questions',
            },
        ),
        migrations.CreateModel(
            name='UserPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('paperId', models.IntegerField(unique=True)),
                ('paperDes', models.TextField()),
                ('number_of_questions', models.IntegerField()),
            ],
            options={
                'db_table': 'user_paper',
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('paperId', models.IntegerField()),
                ('paperDes', models.TextField()),
                ('number_of_questions', models.IntegerField()),
                ('user_score', models.IntegerField()),
                ('questions', djongo.models.fields.ArrayField(model_container=question_generator.models.QuestionResponse)),
            ],
            options={
                'db_table': 'user_responses',
            },
        ),
        migrations.AddIndex(
            model_name='userpaper',
            index=models.Index(fields=['paperId'], name='user_paper_paperId_f390f9_idx'),
        ),
    ]
