# Generated by Django 4.1.13 on 2024-05-05 15:11

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('options', djongo.models.fields.JSONField()),
                ('correct_answer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'generated_questions',
            },
        ),
    ]
