# Generated by Django 4.1.13 on 2024-08-18 17:37

import datetime
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedITQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('options', djongo.models.fields.JSONField()),
                ('correct_answer', models.CharField(max_length=100)),
                ('paperId', models.IntegerField()),
                ('generated_datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'generated_IT_questions',
            },
        ),
        migrations.CreateModel(
            name='UserPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('paperId', models.IntegerField(unique=True)),
                ('paperDes', models.TextField()),
                ('number_of_questions', models.IntegerField()),
            ],
            options={
                'db_table': 'user_paper',
            },
        ),
    ]
