# Generated by Django 4.1.13 on 2024-08-19 16:27

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('question_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('paperId', models.IntegerField()),
                ('number_of_questions', models.IntegerField()),
                ('user_score', models.IntegerField()),
            ],
            options={
                'db_table': 'user_responses',
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question', models.TextField()),
                ('options', djongo.models.fields.JSONField()),
                ('answered_correct', models.BooleanField()),
                ('user_answer', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('user_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question_generator.userresponse')),
            ],
            options={
                'db_table': 'question_responses',
            },
        ),
    ]
