# Generated by Django 4.1.13 on 2024-05-05 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='generatedquestion',
            table=None,
        ),
    ]
