# Generated by Django 4.1.13 on 2024-05-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_generator', '0002_alter_generatedquestion_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='generatedquestion',
            table='generated_questions',
        ),
    ]
